import { defineConfig, type ServerOptions } from "vite";
import { getHttpsServerOptions } from "office-addin-dev-certs";

// The task pane is served from src/taskpane so it is reachable at
// https://localhost:3000/taskpane.html (matching manifest.xml).
//
// Office requires HTTPS, so we serve with trusted localhost certificates
// generated by office-addin-dev-certs. Run once before `npm run dev`:
//   npx office-addin-dev-certs install
//
// Requests to the backend are proxied under /api. Serving them same-origin
// avoids mixed-content blocking (HTTPS page -> HTTP API) and CORS during
// local development. The backend still sets CORS headers for direct calls.
export default defineConfig(async ({ command }) => {
  // HTTPS certificates are only needed for the dev server. Production builds
  // (command === "build") must not require certs to be installed.
  let https: ServerOptions["https"];
  if (command === "serve") {
    const httpsOptions = await getHttpsServerOptions();
    https = { key: httpsOptions.key, cert: httpsOptions.cert };
  }

  return {
    root: "src/taskpane",
    server: {
      port: 3000,
      strictPort: true,
      https,
      proxy: {
        "/api": {
          target: "http://localhost:8080",
          changeOrigin: true,
          rewrite: (path: string) => path.replace(/^\/api/, ""),
        },
      },
    },
    build: {
      outDir: "../../dist",
      emptyOutDir: true,
      rollupOptions: {
        // Entry is taskpane.html (Vite defaults to index.html otherwise).
        input: "src/taskpane/taskpane.html",
      },
    },
  };
});
